### ISSUE TITLE
Feature Request: serde serialize and deserialize derives for RawTag

### ISSUE THREAD

**Issue by TheFern2** [Joylei/plctag-rs#1]
I don't know if you're open to a PR to implement serde serialize and deserialize for RawTag. I read online that libs can implement a feature flag to enable this on or off, I'd like to submit a PR for this. For example tauri-app manages state and uses serde for serialization, but is nearly impossible to do a remote derive or at least I couldn't find a sane way to do it. I ended up forking and adding it to my fork just for testing purposes.

```rust
use serde::{Serialize, Deserialize};

/// wrapper of tag model based on `libplctag`
#[derive(Debug, Serialize, Deserialize)]
pub struct RawTag {
    tag_id: i32,
}
```

**Comment by Joylei** [comment]
I do not think it's a good idea to serialize `RawTag`. 

There must be other ways to get things done.  Can you share some code to show what you're trying to do?

**Comment by TheFern2** [comment]
I apologize I am a bit new to rust in general, I was doing some naughty things and one of the compiler errors was to serialize the state I was managing for tauri-app rust backend, then got errors to serialize my struct and RawTag was part of my struct and needed to be serialized, but I then followed the examples provided by tauri-app on how to manage mutable state and there is absolutely no need to serialize if done correctly.

Closing as there is no issue.
