### ISSUE TITLE
How to static link libplctag for windows ?

### ISSUE THREAD

**Issue by toplinuxsir** [Joylei/plctag-rs#4]
How to static link libplctag for windows ?
Thanks!

**Comment by Joylei** [comment]
please refer to https://github.com/Joylei/plctag-rs/tree/master/crates/sys#static-build

**Comment by toplinuxsir** [comment]
@Joylei  Thanks , I compile in windows(powershell) ,
```
$env:PLCTAG_STATIC="yes"
cargo build --release
```
run the build application , error for not find plctag.dll


Can you explain more detail  ?
Thanks!

**Comment by Joylei** [comment]
set PLCTAG_STATIC to one of "1", "true", "on"

**Comment by toplinuxsir** [comment]
@Joylei Thanks! It works!
