### ISSUE TITLE
Feature request: derive Clone for RawTag

### ISSUE THREAD

**Issue by bremby** [Joylei/plctag-rs#5]
Hi!
The way we set up communications with devices requires us to have RawTag cloneable. There is no risk of race conditions or anything like that that might result in concurrent access to the same tag. But what we do is create an abstraction over tags, which, when it's un-abstracted, requires a clone call. My guess is that by omitting both Copy and Clone you enforce local ownership and thus synchronized access at any time, but it severely limits architectural options. Would you agree on adding that Clone derive to RawTag? I don't know what other structs may be needed too, as I started using your nice library just yesterday. :)

And thanks for making this!

**Comment by Joylei** [comment]
I do not think it's a good idea.

What about `Arc<RawTag>`?

**Comment by bremby** [comment]
I spoke with a colleague about this. We will wrap it in an Arc, but probably also in a mutex, because if your intent is to enforce local ownership, you should mark it as `!Sync`. So having both Mutex and Arc should be required to use that struct, if you want to synchronize tag access*. Feel free to close this issue now. Thank you! :)

*) I'm not sure if only tags require synchronization. The [original documentation](https://github.com/libplctag/libplctag/wiki/API#controlling-multi-threaded-access-to-a-tag) talks both about tags and the API itself, so I'm not sure whether one needs to synchronize over all calls to all (most) API functions.

**Comment by Joylei** [comment]
you should use mutex to protect read/write. you cannot read and write at the same time，and get an error code if it's busy. with mutex，operations from different threads are in order.

**Comment by bremby** [comment]
I don't understand - what do you mean you "can't" read and write at the same time? Without Arc and without Clone or Copy, you can't read and read at the same time either, because there's only one RawTag instance. If you wrap it in Arc, you can theoretically do read twice or read and write at the same time. And if you get an error when busy, why not just derive Clone anyway?

**Comment by Joylei** [comment]
with Arc，the tag only drop once.  if rawtag is clonable， it will drop multiple times if there are multiple instances for the same tag. that's the problem.

**Comment by bremby** [comment]
Oh, I didn't know you destroy the tag on drop. Alright, that makes sense. Thanks! :+1:
